spring:
  application:
    name: micro-gateway
  profiles: 
    active: local
    
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8 #编码格式
    
  ##################### DB #####################
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT user()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    
#  mvc: 
#    ignore-default-model-on-redirect: false
#    locale: zh_CN
#    view: 
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  http: 
    encoding: 
      enabled: true
      charset: UTF-8
      force: true

eureka:
    instance:
        preferIpAddress: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
        lease-renewal-interval-in-seconds: 5    ## 续约更新时间间隔（默认30秒）
        lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
    client:
        registry-fetch-interval-seconds: 5 # 抓取服务列表
        serviceUrl:
            defaultZone: http://localhost:8881/eureka/
        
            
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

endpoints: 
  health: 
    sensitive: false
  
feign:
  hystrix:
    enabled: true
  compression: 
    request: 
      enabled: true # 配置请求GZIP压缩
      mime-types: ["text/xml","application/xml","application/json"] # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response: 
      enabled: true # 配置响应GZIP压缩
      
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 32000  # 设置熔断超时时间  default 1000
        timeout: 
          enabled: true # 打开超时熔断功能 default true
    

ribbon:
  ConnectTimeout: 2000 # 设置连接超时时间 default 2000
  ReadTimeout: 6000    # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 1    # 切换实例的重试次数  default 1
  MaxAutoRetries: 1     # 对当前实例的重试次数 default 0
    
    
zuul: 
  retryable: true
  ignoredServices: '*'
  routes: 
    #micro-user:
     # stripPrefix: false
     # path: /user/**
    micro-resource:
      stripPrefix: false
      path: /**

security: 
  basic: 
    enabled: false



